CREATE DATABASE IF NOT EXISTS  student_ms;
USE student_ms;

CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100)UNIQUE NOT NULL,
    password VARCHAR(255)NOT NULL
);

CREATE TABLE massages(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100)NOT NULL,
    massage TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);